[package]
name = "pi-web-backend"
version = "0.1.0"
authors = ["BrilliantPhal <phalbrilliant@gmail.com>"]
edition = "2018"


[dependencies]
async-graphql-actix-web = "1.17.3"
actix-cors = "0.2.0"
actix-web = "2.0.0"
actix-rt = "1.1.1"
actix-web-actors = "2.0.0"
async-graphql = "1.17"
slab = "0.4.2"
listenfd = "0.3.3"
serde = "1.0.115"
serde_derive = "1.0.115"
serde_json = "1.0.57"
strum = "0.19.2"
strum_macros = "0.19.2"
tokio = { version = "0.2", features = ["time", "stream"] }
futures = "0.3.5"
mongodb = { version = "1.1.0" }
bson = "1.1.0"
uuid = "0.8.1"
syn = "1.0.39"
bcrypt = "0.8.2"
dotenv = "0.15.0"
jsonwebtoken = "7.2.0"
# mail = { version = "0.7.0", features = ["handlebars_templates"] }
# failure = "0.1.8"
# soft-ascii-string = "1.1.0"
# mail-template = "0.6.1"